---
- name: Uninstall a webserver
  hosts: web
  become: true
  tasks:

    - name: Ensure nginx stopped
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Ensure nginx is uninstalled
      ansible.builtin.package:
        name: nginx
        state: abcent
