- name: Copy files
  hosts: web
  become: true
  tasks:

    - name: Copy local file to /etc/nginx/conf.d/https.conf
      ansible.builtin.copy:
        src: files/https.conf
        dest: /etc/nginx/conf.d/https.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
