- name: Copy files
  hosts: web
  become: true
  tasks:

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/example.internal/html/
        state: directory
        mode: '0755'
        setype: _default


    - name: Copy local file to /etc/nginx/conf.d/https.conf
      ansible.builtin.copy:
        src: files/https.conf
        dest: /etc/nginx/conf.d/https.conf
        owner: root
        group: root
        mode: '0644'


    - name: Copy local file to /etc/nginx/conf.d/index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Show IP-adress
      ansible.builtin.debug:
        msg: "Serverns IP-adress är {{ ansible_default_ipv4.address }}"

    - name: Deploy Nginx configuration from template
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart nginx service
      when: changed is true
      ansible.builtin.service:
        name: nginx
        state: reloaded
