- name: Copy files to db
  hosts: db
  become: true
  tasks:

    - name: Copy each file over that matches the given pattern
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/deploy/
        owner: deploy
        group: deploy
        mode: "0664"
      with_fileglob:
        - "files/*.md"
